# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ratingg.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from backend import *

class Ui_Rating(object):
        def __init__(self,id_produk):
                super().__init__()
                self.pushButton = QtWidgets.QPushButton("Submit")
                self.data = getProduct(id_produk)
                self.comboBox = QtWidgets.QComboBox()
                self.lineEdit = QtWidgets.QLineEdit()

        #         id_barang, nama_barang, nama_toko, stok, panjang, lebar, tinggi, berat, harga, foto,
        # deskripsi, alamat_toko FROM katalog, toko 

        def setupUi(self, Form):
                Form.setObjectName("Form")
                Form.resize(824, 494)
                self.verticalLayout = QtWidgets.QVBoxLayout(Form)
                self.verticalLayout.setObjectName("verticalLayout")
                
                if (len(self.data) > 0):
                        a = self.data[0]
                        self.widget = QtWidgets.QWidget(Form)
                        self.widget.setStyleSheet("background-color:rgb(252, 240, 204);\n"
                                "border-radius:30px;\n"
                                "border:10 px solid black;")
                        self.widget.setObjectName("widget")
                        self.label = QtWidgets.QLabel(self.widget)
                        self.label.setText("Rating")
                        self.label.setGeometry(QtCore.QRect(38, 14, 121, 48))
                        self.label.setStyleSheet("color:rgb(134, 22, 87);font: 28pt \"Times New Roman\";")
                        self.label.setObjectName("label")
                        self.widget_2 = QtWidgets.QWidget(self.widget)
                        self.widget_2.setGeometry(QtCore.QRect(30, 70, 651, 171))
                        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
                        self.widget_2.setObjectName("widget_2")
                        self.label_2 = QtWidgets.QLabel(self.widget_2)
                        self.label_2.setText(str(a[2]))
                        self.label_2.setGeometry(QtCore.QRect(180, 10, 161, 21))
                        self.label_2.setStyleSheet("font: 14pt \"Times New Roman\";\n"
                                "color: rgb(149, 149, 149);")
                        self.label_2.setObjectName("label_2")
                        self.label_3 = QtWidgets.QLabel(self.widget_2)
                        self.label_3.setText(str(a[1]))
                        self.label_3.setGeometry(QtCore.QRect(180, 40, 161, 31))
                        self.label_3.setStyleSheet("font: 20pt \"Times New Roman\";")
                        self.label_3.setObjectName("label_3")
                        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
                        self.lineEdit.setGeometry(QtCore.QRect(180, 110, 361, 31))
                        self.lineEdit.setStyleSheet("background-color: rgb(216, 216, 216);font: 12pt \"Times New Roman\";border-radius:10px")
                        self.lineEdit.setObjectName("lineEdit")
                        self.pushButton = QtWidgets.QPushButton(self.widget_2)
                        self.pushButton.setText("Submit")
                        self.pushButton.setGeometry(QtCore.QRect(550, 110, 91, 31))
                        self.pushButton.setStyleSheet('''
                                QPushButton{
                                        background-color: rgb(195, 195, 195);
                                        border-radius:10px;
                                        font: 12pt \"Times New Roman\";
                                }
                                QPushButton::hover{
                                        background-color: rgb(252, 240, 204);
                                        color:#861657;
                                }
                        ''')
                        self.pushButton.setObjectName("pushButton")
                        self.comboBox = QtWidgets.QComboBox(self.widget_2)
                        self.comboBox.setGeometry(QtCore.QRect(290, 80, 69, 22))
                        self.comboBox.setStyleSheet("background-color: rgb(207, 207, 207);\n"
                                "font: 14pt \"Times New Roman\";")
                        self.comboBox.setObjectName("comboBox")
                        self.comboBox.addItem("")
                        self.comboBox.addItem("")
                        self.comboBox.addItem("")
                        self.comboBox.addItem("")
                        self.comboBox.addItem("")
                        self.comboBox.setItemText(0, "1")
                        self.comboBox.setItemText(1, "2")
                        self.comboBox.setItemText(2, "3")
                        self.comboBox.setItemText(3, "4")
                        self.comboBox.setItemText(4, "5")
                        self.label_4 = QtWidgets.QLabel(self.widget_2)
                        self.label_4.setText("Rating")
                        self.label_4.setGeometry(QtCore.QRect(180, 80, 91, 20))
                        self.label_4.setStyleSheet("font: 14pt \"Times New Roman\";")
                        self.label_4.setObjectName("label_4")
                        self.label_5 = QtWidgets.QLabel(self.widget_2)     
                        self.label_5.setGeometry(QtCore.QRect(30, 15, 120, 131))
                        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
                        sizePolicy.setHorizontalStretch(0)
                        sizePolicy.setVerticalStretch(0)
                        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
                        self.label_5.setSizePolicy(sizePolicy)
                        self.label_5.setMaximumSize(QtCore.QSize(130, 90000))

                        self.label_5.setObjectName("label_5")
                        pixmap = QtGui.QPixmap()
                        pixmap.loadFromData(a[9])
                        
                        # adding image to label
                        self.label_5.setPixmap(pixmap)

                        # Optional, resize label to image size
                        self.label_5.resize(pixmap.width(),
                                        pixmap.height())

                        self.label_6 = QtWidgets.QLabel(self.widget_2)
                        self.label_6.setGeometry(QtCore.QRect(496, 150, 141, 16))
                        self.label_6.setObjectName("label_6")
                        

                        self.verticalLayout.addWidget(self.widget)


                        QtCore.QMetaObject.connectSlotsByName(Form)
     

        
      

