# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ratingg.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from backend import getTransaksi

class Ui_Transaksi(object):
        def __init__(self,user_id):
                super().__init__()
                self.pushButton = QtWidgets.QPushButton("Beri Rating")
                self.data = getTransaksi(user_id)
                self.comboBox = QtWidgets.QComboBox()
                self.ratingbuttonlist = []
                self.idbarang = []

        def setupUi(self, Form):
                ScrollArea = QtWidgets.QScrollArea()
                Form.setObjectName("Form")
                Form.resize(824, 494)
                self.verticalLayout = QtWidgets.QVBoxLayout(Form)
                self.verticalLayout.setObjectName("verticalLayout")
                self.verticalLayout.setSpacing(10)
                counter = 0
            
                for a in self.data:
                        self.widget = QtWidgets.QWidget(Form)
                        self.widget.setMinimumHeight(100)
                        self.widget.setStyleSheet("background-color:rgb(252, 240, 204);\n"
                                "border-radius:30px;\n"
                                "border:10 px solid black;")
                        self.widget.setObjectName("widget")
                        self.label = QtWidgets.QLabel(self.widget)
                        self.label.setText("Riwayat Transaksi")
                        self.label.setGeometry(QtCore.QRect(38, 14, 271, 48))
                        self.label.setStyleSheet("color:rgb(134, 22, 87);font: 28pt \"Times New Roman\";")
                        self.label.setObjectName("label")
                        
                        self.widget_2 = QtWidgets.QWidget(self.widget)
                        
                        self.widget_2.setGeometry(QtCore.QRect(30, 70, 631, 191))
                        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
                        self.widget_2.setObjectName("widget_2")
                        self.label_3 = QtWidgets.QLabel(self.widget_2)
                        self.label_3.setText("Id Transaksi      :" +str(a[0]))
                        self.label_3.setGeometry(QtCore.QRect(20, 10, 551, 31))
                        self.label_3.setStyleSheet("font: 16pt \"Times New Roman\";")
                        self.label_3.setObjectName("label_3")
                        self.label_4 = QtWidgets.QLabel(self.widget_2)
                        self.label_4.setText("Nama Toko     :" +str(a[1]))
                        self.label_4.setGeometry(QtCore.QRect(20, 40, 581, 31))
                        self.label_4.setStyleSheet("font: 16pt \"Times New Roman\";")
                        self.label_4.setObjectName("label_4")
                        self.label_5 = QtWidgets.QLabel(self.widget_2)
                        self.label_5.setText("Nama Produk  :" +str(a[6]))
                        self.label_5.setGeometry(QtCore.QRect(20, 70, 581, 31))
                        self.label_5.setStyleSheet("font: 16pt \"Times New Roman\";")
                        self.label_5.setObjectName("label_5")
                        self.label_7 = QtWidgets.QLabel(self.widget_2)
                        self.label_7.setText("Id Pesanan    :" +str(a[3]))
                        self.label_7.setGeometry(QtCore.QRect(20, 100, 571, 31))
                        self.label_7.setStyleSheet("font: 16pt \"Times New Roman\";")
                        self.label_7.setObjectName("label_7")
                        self.label_8 = QtWidgets.QLabel(self.widget_2)
                        self.label_8.setText("Status    :" +str(a[4]))
                        self.label_8.setGeometry(QtCore.QRect(20, 130, 571, 31))
                        self.label_8.setStyleSheet("font: 16pt \"Times New Roman\";")
                        self.label_8.setObjectName("label_8")
                        self.label_9 = QtWidgets.QLabel(self.widget_2)
                        self.label_9.setText("Metode Pembayaran     :" +str(a[5]))
                        self.label_9.setGeometry(QtCore.QRect(20, 160, 571, 31))
                        self.label_9.setStyleSheet("font: 16pt \"Times New Roman\";")
                        self.label_9.setObjectName("label_9")
                        self.ratingbuttonlist.append(QtWidgets.QPushButton(self.widget))
                        self.ratingbuttonlist[counter].setText("Beri Rating")
                        self.ratingbuttonlist[counter].setGeometry(QtCore.QRect(500, 120, 131, 61))
                        self.ratingbuttonlist[counter].setStyleSheet("QPushButton{background-color:#861657;\n"
                        "color:#FCF0CC;\n"
                        "font-size:15px;\n"
                        "font-weight:400;\n"
                        "text-align:center;\n"
                        "padding:8% 3%;\n"
                        "border-style: outset;\n"
                        "border-radius:25px;}\n"
                        "QPushButton:hover\n"
                        "{\n"
                        "   background-color:#A64253;\n"
                        "}\n"
                        "          ")
                        self.idbarang.append(a[8])
                        self.ratingbuttonlist[counter].setObjectName("pushButton")
                        self.verticalLayout.addWidget(self.widget)
                        counter+=1
        
                QtCore.QMetaObject.connectSlotsByName(Form)